export const assets = {
  onboarding: {
    // slide1: require("./images/top-facilities-image.png"),
    slide1: require("./images/first-onboarding-img.png"),
    slide2: require("./images/second-onboarding-img.jpg"),
    slide3: require("./images/third-onboarding-img.jpg"),
  },
  icons: {
    app_icon: require("./icons/App-launcher-icon.png"),
    user_icon: require("./icons/user-icon.png"),
    google_icon: require("./icons/google-icon.png"),
    facebook_icon: require("./icons/fb-icon.png"),
    profile_icon: require("./icons/profile-icon-tab.png"),
    order_icon: require("./icons/order-icon-tab.png"),
    home_icon: require("./icons/home-icon-tab.png"),
    scooter_icon: require("./icons/scooter-icon.png"),
    dropoff_icon: require("./icons/dropoff-icon.png"),
    location_icon: require("./icons/location-icon.png"),
    recurring_icon: require("./icons/recurring-icon.png"),
    setting_icon: require("./icons/setting-icon.png"),
    msg_icon: require("./icons/msg-icon.png"),
    faq_icon: require("./icons/faq-icon.png"),
    logout_icon: require("./icons/logout-icon.png"),
    menu_icon: require("./icons/menu-icon.png"),
    clock_icon: require("./icons/clock-icon.png"),
    info_icon_fill: require("./icons/info-icon-fill.png"),
  },
  images: {
    profile_placeholder: require("./images/profile-placeholder.png"),
  },
};
